server:
  port: 8081


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://172.19.12.80:5432/dev
    username: dev
    password: '123456'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
# spring session相关配置
  session:
    store-type: redis
    redis:
      namespace: 'gnrd:session'
    timeout: 30m
  redis:
    redisson:
      file: classpath:redisson.yaml

uid:
  epoch-str: '2024-05-01'

rsa:
  private-key: 'MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDjGDxcRjz3Cvg/0NAZF15GV0uTs+yce3rOC+b4noI2143vfeWW7w6lVMkBcuFVeDg22PZ74oSCEd34LII6vLy7SIuGcfiP9mt1zX7FhGQG+3ZlzFvbQ7tctYmiW1s1nW4ej9Nw6EM6BfUxjdS8qjG8MCnRaPkSrwYrQ1sddFkQ2atDU7U64Mfm4nkwQHtx4XwxzQ/BXmySTQR+s8vpLl0ZS6VztCGinKcEtf+IoY4n8tfJc+nlelpW6Ht027+sAB6Be59ErirzOZ9SuZOus511JQyY0EAU5matuaIuagT3nQeAjktWD14sIFFWniDBA9oRBi34BPfbe6s0njESQWl7AgMBAAECggEADnUko2oNuvT8U/4kjKX9TwFP776hkcUv6GRylzs3WZ8RS4ENqxvCDqPrF65rV3uLwwlYbw+loi0M0oSgfKidlvDDgGyXrf0HePYugj88KdBvIh3HohoNGHxh0q/G16itPsENhx+KTbkP+jbBp4pp5MWBZaV6TrmzOb4UIJ5sUyzhr6eHQmqXFaMuWCrroIACSIRsnEJjWlWYuTHKB8Vo+JmpvP3givvJfWrkh12krpKRW3cLk6AIZT6cvSO+5PtRY02jpeeoY6l5czCTCOQaWR+VSfTgg72t3kdM68mBnIafJzzNRg6WaBxhg7IJBoBtooMs2m4T3VNjfD56Udmm4QKBgQD5VztNLtKT5uLFkp17YR1fpT6vJ6qZuSsMhlVGckaSP2uQ0KQtMOzY66INI2RJARitcmjRY45c99tfOoxXDEttnt/Kus8Se1qU7RP2evSjRY9ETWUCJT3zJArLfgeiYG607+BaONevSBUhVmH/O8VewStiazJoCpYhehFFJjDZmwKBgQDpKOfJSHI4n+dOozKkwK/QzVrZFpayWiOUKtjN7fjx+lMwsTKzAMm2LkJqdJFrGzQefv+3sz8F4HPnGgZqj6EoIAs6GBJ7gnORHvS7g79E91sGsTmAZaK+msj7nt198ptng9PyGsDa7tfipLYv7lVHnChdY6sfLsN1qbdjlcYdoQKBgQDxENdyvew1tqpVHnVHjhMaH+dE7PLSAOaQC2hy3ZVBXDOhJTc1wfGbn+VjEm6o7nhvaQfSOZCwbaoYncCFgIuEhnATzxzY344qIjSEv0e6e0wSW0lnE56bbqNJLqYu5VDjem/MitxsySI0wxGn9J/UBqrtUnq/gEy6PQxpcI0WNQKBgQDeq/c5Dxwuod/pBQjvuSnvsr8phl4jNNy3u3fUq4nNpvDeFszBkWYSu/kn6+2ZKaDL4yPaz6/HsAVg10T7bfJN/NRcBfNYy0wNc0/s6TS467aeHJE641XazL5XN/B2QUVTRd4bYJuAOwwoYn+wJOCDBEq0beRWYnW/IHeI/tf3IQKBgQDeeYIZoHo7Fy8uTqAfG2qvN47andswrQ6KQ0JElmXyzmA8wvcQfgYXPj3dCagoSRa1pzDY+7Ni99jOLPNFxLSd01PhKR4RFG6gTZiOnPH39MSW8MtJ4sAOPW9nJErHtEZA6curIjfahzaMpFy86zML6smxdefMHJ5rAGU8zf8+qg=='

